version: "1.0"
services:
  micronaut-java:
    build:
      context: : .
    ports:
      - 8000:8000
      - 8080:8080
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_HOST=http://localhost
      - DB_PORT="5432"
      - DB_NAME="java"
      - DB_USER="postgres"
      - DB_PASSWORD="password"
    volumes:
    - ./:/app

  postgres:
    image: library/postgres:latest
    ports:
      - 3306:3306
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DATABASE=java
    volumes:
      - postgres_data:/var/lib/postgres
      - postgres_config:/etc/postgres/conf.d



